var shuffleSequence = seq("intro", "reminder", sepWith("practiceSep","practice"), 
                          sepWith("sep", randomize(rshuffle(shuffle("a", "b", "c", "d", "f1", "f2", 
                                                  "f3", "f4", "f5", "f6", "f7", 
                                                  "f8", "f9", "f10", "f11", "f12", 
                                                  "f13", "f14", "f15", "f16", "f17", 
                                                  "f18", "f19", "f20", "f21", "f22", 
                                                  "f23", "f24", "f25", "f26", "f27", 
                                                  "f28", "f29", "f30", "f31", "f32", 
                                                  "f33", "f34", "f35", "f36", "f37", 
                                                  "f38", "f39", "f40", "f41", "f42", 
                                                  "f43", "f44", "f45", "f46", "f47", "f48")))));

var practiceItemTypes = ["practice"];

var defaults = [
    "Separator", { transfer: "keypress",
                   normalMessage: "Press any key for next sentence.",
                   errorMessage: "Too slow! Press any key for next sentence." },
    "DashedAcceptabilityJudgment", {display: "in place",
                             blankText: "\u002B",
                            q: "Was that a good sentence?",
                               as: [["f","Yes"],["j","No"]],
                               timeout: 3000,
                            randomOrder: false,
                            showNumbers: false,
                            presentAsScale: true,
                            leftComment: "(F)",
                            rightComment: "(J)"},
    "Message", { hideProgressBar: true },
    "Form", { hideProgressBar: true }
];

var counterOverride = 4;

var items = [

["sep", "Separator", { }],

["reminder","Separator", {normalMessage: "Remember: Keep your fingers on the F (YES) and J (NO) keys so you're ready to respond quickly. Press any key to see the first sentence." }],

["practiceSep", "Separator", { normalMessage: "Press any key for next sentence.",
                        errorMessage: "Wrong! Press any key for next sentence."}],

["intro", "Form", {html: { include: "example_intro.html" },
                    validators: {age: function (s) { if (s.match(/^\d+$/)) return true;                             else return "Bad value for \u2018age\u2019"; } }}],

["instructions","Message", { html: { include: "WhWh-instructions.html" }}],

//Manually send results
["sr", "__SendResults__", { }],
["code","Message",{html: { transfer: null, include: "WhWh-end.html" }}],

//Practice
["practice", "DashedAcceptabilityJudgment", {s: "The sentences will be presented like this.", 
    q: "Are you following this?"}],
    ["practice", "DashedAcceptabilityJudgment", {s: "The man accidently hurt himself", hasCorrect: 0}],
        ["practice", "DashedAcceptabilityJudgment", {s: "The assistant accidently kicking her sister under the table.", hasCorrect: 1}],
        ["practice", "DashedAcceptabilityJudgment", {s: "The children at the park amused themselves all day long", hasCorrect: 0}],
        ["practice", "DashedAcceptabilityJudgment", {s: "The salesman openly describing his boss as a helpful person.", hasCorrect: 1}],
        ["practice", "DashedAcceptabilityJudgment", {s: "The seamstress accidently pinched her finger in the sewing machine.", hasCorrect: 0}],

    
// Items
    
[["a", 1], "DashedAcceptabilityJudgment", {s: "The man recently hurt himself while playing football in the park."}],
[["b", 1], "DashedAcceptabilityJudgment", {s: "The woman recently hurt himself while playing football in the park. "}],
[["c", 1], "DashedAcceptabilityJudgment", {s: "The women recently hurt himself while playing football in the park. "}],
[["d", 1], "DashedAcceptabilityJudgment", {s: "We recently hurt himself while playing football in the park."}],
[["a", 2], "DashedAcceptabilityJudgment", {s: "The nurse accidently pricked herself with a used syringe."}],
[["b", 2], "DashedAcceptabilityJudgment", {s: "The doctor accidently pricked herself with a used syringe."}],
[["c", 2], "DashedAcceptabilityJudgment", {s: "The doctors accidently pricked herself with a used syringe."}],
[["d", 2], "DashedAcceptabilityJudgment", {s: "We accidently pricked herself with a used syringe."}],
[["a", 3], "DashedAcceptabilityJudgment", {s: "The father often blamed himself for the recent accident."}],
[["b", 3], "DashedAcceptabilityJudgment", {s: "The mother often blamed himself for the recent accident."}],
[["c", 3], "DashedAcceptabilityJudgment", {s: "The mothers often blamed himself for the recent accident."}],
[["d", 3], "DashedAcceptabilityJudgment", {s: "We often blamed himself for the recent accident."}],
[["a", 4], "DashedAcceptabilityJudgment", {s: "The pilot recently injured himself quite badly during the journey."}],
[["b", 4], "DashedAcceptabilityJudgment", {s: "The stewardess recently injured himself quite badly during the journey."}],
[["c", 4], "DashedAcceptabilityJudgment", {s: "The stewardesses recently injured himself quite badly during the journey."}],
[["d", 4], "DashedAcceptabilityJudgment", {s: "We recently injured himself quite badly during the journey."}],
[["a", 5], "DashedAcceptabilityJudgment", {s: "The firefighter accidently cut himself on the broken glass."}],
[["b", 5], "DashedAcceptabilityJudgment", {s: "The secretary accidently cut himself on the broken glass."}],
[["c", 5], "DashedAcceptabilityJudgment", {s: "The secretaries accidently cut himself on the broken glass."}],
[["d", 5], "DashedAcceptabilityJudgment", {s: "We accidently cut himself on the broken glass."}],
[["a", 6], "DashedAcceptabilityJudgment", {s: "The girl proudly taught herself to play the piano."}],
[["b", 6], "DashedAcceptabilityJudgment", {s: "The boy proudly taught herself to play the piano."}],
[["c", 6], "DashedAcceptabilityJudgment", {s: "The boys proudly taught herself to play the piano."}],
[["d", 6], "DashedAcceptabilityJudgment", {s: "We proudly taught herself to play the piano."}],
[["a", 7], "DashedAcceptabilityJudgment", {s: "The schoolgirl carefully disciplined herself to study more often."}],
[["b", 7], "DashedAcceptabilityJudgment", {s: "The schoolboy carefully disciplined herself to study more often."}],
[["c", 7], "DashedAcceptabilityJudgment", {s: "The schoolboys carefully disciplined herself to study more often."}],
[["d", 7], "DashedAcceptabilityJudgment", {s: "We carefully disciplined herself to study more often."}],
[["a", 8], "DashedAcceptabilityJudgment", {s: "The nun recently taught herself how to read Latin."}],
[["b", 8], "DashedAcceptabilityJudgment", {s: "The priest recently taught herself how to read Latin."}],
[["c", 8], "DashedAcceptabilityJudgment", {s: "The priests recently taught herself how to read Latin."}],
[["d", 8], "DashedAcceptabilityJudgment", {s: "We recently taught herself how to read Latin."}],
[["a", 9], "DashedAcceptabilityJudgment", {s: "The actress really owed herself another chance to get the role."}],
[["b", 9], "DashedAcceptabilityJudgment", {s: "The actor really owed herself another chance to get the role."}],
[["c", 9], "DashedAcceptabilityJudgment", {s: "The actors really owed herself another chance to get the role."}],
[["d", 9], "DashedAcceptabilityJudgment", {s: "We really owed herself another chance to get the role."}],
[["a", 10], "DashedAcceptabilityJudgment", {s: "The secretary recently motivated herself to get a higher degree."}],
[["b", 10], "DashedAcceptabilityJudgment", {s: "The plumber recently motivated herself to get a higher degree."}],
[["c", 10], "DashedAcceptabilityJudgment", {s: "The plumbers recently motivated herself to get a higher degree."}],
[["d", 10], "DashedAcceptabilityJudgment", {s: "We recently motivated herself to get a higher degree."}],
[["a", 11], "DashedAcceptabilityJudgment", {s: "The waiter repeatedly reminded himself about the outstanding orders."}],
[["b", 11], "DashedAcceptabilityJudgment", {s: "The waitress repeatedly reminded himself about the outstanding orders."}],
[["c", 11], "DashedAcceptabilityJudgment", {s: "The waitresses repeatedly reminded himself about the outstanding orders."}],
[["d", 11], "DashedAcceptabilityJudgment", {s: "We repeatedly reminded himself about the outstanding orders."}],
[["a", 12], "DashedAcceptabilityJudgment", {s: "The cheerleader secretly blamed herself for losing the difficult competition."}],
[["b", 12], "DashedAcceptabilityJudgment", {s: "The football player secretly blamed herself for losing the difficult competition."}],
[["c", 12], "DashedAcceptabilityJudgment", {s: "The football players secretly blamed herself for losing the difficult competition."}],
[["d", 12], "DashedAcceptabilityJudgment", {s: "We secretly blamed herself for losing the difficult competition."}],
[["a", 13], "DashedAcceptabilityJudgment", {s: "The businesswoman happily treated herself to a piece of chocolate cake."}],
[["b", 13], "DashedAcceptabilityJudgment", {s: "The businessman happily treated herself to a piece of chocolate cake."}],
[["c", 13], "DashedAcceptabilityJudgment", {s: "The businessmen happily treated herself to a piece of chocolate cake."}],
[["d", 13], "DashedAcceptabilityJudgment", {s: "We happily treated herself to a piece of chocolate cake."}],
[["a", 14], "DashedAcceptabilityJudgment", {s: "The businessman proudly introduced herself to the wealthy CEO."}],
[["b", 14], "DashedAcceptabilityJudgment", {s: "The receptionist proudly introduced herself to the wealthy CEO."}],
[["c", 14], "DashedAcceptabilityJudgment", {s: "The receptionists proudly introduced herself to the wealthy CEO."}],
[["d", 14], "DashedAcceptabilityJudgment", {s: "We proudly introduced herself to the wealthy CEO."}],
[["a", 15], "DashedAcceptabilityJudgment", {s: "The salesman secretly disliked himself quite a lot."}],
[["b", 15], "DashedAcceptabilityJudgment", {s: "The saleswoman secretly disliked himself quite a lot."}],
[["c", 15], "DashedAcceptabilityJudgment", {s: "The saleswomen secretly disliked himself quite a lot."}],
[["d", 15], "DashedAcceptabilityJudgment", {s: "We secretly disliked himself quite a lot."}],
[["a", 16], "DashedAcceptabilityJudgment", {s: "The boy quietly amused himself at the boring recital."}],
[["b", 16], "DashedAcceptabilityJudgment", {s: "The girl quietly amused himself at the boring recital."}],
[["c", 16], "DashedAcceptabilityJudgment", {s: "The girls quietly amused himself at the boring recital."}],
[["d", 16], "DashedAcceptabilityJudgment", {s: "We quietly amused himself at the boring recital."}],
[["a", 17], "DashedAcceptabilityJudgment", {s: "The policewoman carefully familiarized herself with all the strict regulations."}],
[["b", 17], "DashedAcceptabilityJudgment", {s: "The policeman carefully familiarized herself with all the strict regulations."}],
[["c", 17], "DashedAcceptabilityJudgment", {s: "The policemen carefully familiarized herself with all the strict regulations."}],
[["d", 17], "DashedAcceptabilityJudgment", {s: "We carefully familiarized herself with all the strict regulations."}],
[["a", 18], "DashedAcceptabilityJudgment", {s: "The congresswoman repeatedly reminded herself about the new laws."}],
[["b", 18], "DashedAcceptabilityJudgment", {s: "The congressman repeatedly reminded herself about the new laws."}],
[["c", 18], "DashedAcceptabilityJudgment", {s: "The congressmen repeatedly reminded herself about the new laws."}],
[["d", 18], "DashedAcceptabilityJudgment", {s: "We repeatedly reminded herself about the new laws."}],
[["a", 19], "DashedAcceptabilityJudgment", {s: "The actress really embarrassed herself in front of the harsh audience. "}],
[["b", 19], "DashedAcceptabilityJudgment", {s: "The cameraman really embarrassed herself in front of the harsh audience.  "}],
[["c", 19], "DashedAcceptabilityJudgment", {s: "The cameramen really embarrassed herself in front of the harsh audience.  "}],
[["d", 19], "DashedAcceptabilityJudgment", {s: "We really embarrassed herself in front of the harsh audience.  "}],
[["a", 20], "DashedAcceptabilityJudgment", {s: "The congresswoman often doubted herself on most major decisions."}],
[["b", 20], "DashedAcceptabilityJudgment", {s: "The soldier often doubted herself on most major decisions."}],
[["c", 20], "DashedAcceptabilityJudgment", {s: "The soldiers often doubted herself on most major decisions."}],
[["d", 20], "DashedAcceptabilityJudgment", {s: "We often doubted herself on most major decisions."}],
[["a", 21], "DashedAcceptabilityJudgment", {s: "The nurse deliberately characterized herself as a helpful person"}],
[["b", 21], "DashedAcceptabilityJudgment", {s: "The soldier deliberately characterized herself as a helpful person"}],
[["c", 21], "DashedAcceptabilityJudgment", {s: "The soldiers deliberately characterized herself as a helpful person"}],
[["d", 21], "DashedAcceptabilityJudgment", {s: "We deliberately characterized herself as a helpful person"}],
[["a", 22], "DashedAcceptabilityJudgment", {s: "The actor intentionally portrayed himself as a kind person"}],
[["b", 22], "DashedAcceptabilityJudgment", {s: "The actress intentionally portrayed himself as a kind person"}],
[["c", 22], "DashedAcceptabilityJudgment", {s: "The actresses intentionally portrayed himself as a kind person"}],
[["d", 22], "DashedAcceptabilityJudgment", {s: "We intentionally portrayed himself as a kind person"}],
[["a", 23], "DashedAcceptabilityJudgment", {s: "The policewoman frequently described herself as an honest cop."}],
[["b", 23], "DashedAcceptabilityJudgment", {s: "The policeman frequently described herself as an honest cop."}],
[["c", 23], "DashedAcceptabilityJudgment", {s: "The policemen frequently described herself as an honest cop."}],
[["d", 23], "DashedAcceptabilityJudgment", {s: "We frequently described herself as an honest cop."}],
[["a", 24], "DashedAcceptabilityJudgment", {s: "The businesswoman happily praised herself for the successful merger."}],
[["b", 24], "DashedAcceptabilityJudgment", {s: "The businessman happily praised herself for the successful merger."}],
[["c", 24], "DashedAcceptabilityJudgment", {s: "The businessmen happily praised herself for the successful merger."}],
[["d", 24], "DashedAcceptabilityJudgment", {s: "We happily praised herself for the successful merger"}],

// Fillers
    
["f1", "DashedAcceptabilityJudgment", {s: "The assistant accidently kicking her sister under the table."}],
["f2", "DashedAcceptabilityJudgment", {s: "The therapist frequently inspiring her clients to achieve more."}],
["f3", "DashedAcceptabilityJudgment", {s: "The lawyer frequently praising his clients for their help."}],
["f4", "DashedAcceptabilityJudgment", {s: "The choirboy quietly calming his friend down after the tragic incident."}],
["f5", "DashedAcceptabilityJudgment", {s: "The prince frequently bringing his friends brand new clothing."}],
["f6", "DashedAcceptabilityJudgment", {s: "The princess recently inspiring her servants to be kinder."}],
["f7", "DashedAcceptabilityJudgment", {s: "The councilman purposely characterizing his staff as hard working."}],
["f8", "DashedAcceptabilityJudgment", {s: "The attorney accidently misrepresenting his client in the controversial court case."}],
["f9", "DashedAcceptabilityJudgment", {s: "The waiter often recommending his friends to the manager."}],
["f10", "DashedAcceptabilityJudgment", {s: "The comedian hilariously portraying his mean father in the new movie."}],
["f11", "DashedAcceptabilityJudgment", {s: "The salesman openly describing his boss as a helpful person."}],
["f12", "DashedAcceptabilityJudgment", {s: "The stock broker erroneously casting his mother in a negative light."}],
["f13", "DashedAcceptabilityJudgment", {s: "The rapper recently branded his crew as lazy."}],
["f14", "DashedAcceptabilityJudgment", {s: "The actress often depicted her idols in her recent films."}],
["f15", "DashedAcceptabilityJudgment", {s: "The seamstress accidently pinched her finger in the sewing machine."}],
["f16", "DashedAcceptabilityJudgment", {s: "The mother often embarrassed her children in the front of the school."}],
["f17", "DashedAcceptabilityJudgment", {s: "The reporter openly characterized her congressman as an idiot. "}],
["f18", "DashedAcceptabilityJudgment", {s: "We unsurprisingly noticing her students cheating on the test."}],
["f19", "DashedAcceptabilityJudgment", {s: "We hesitantly nominated her boss for the award."}],
["f20", "DashedAcceptabilityJudgment", {s: "We often complimented her agent on her gorgeous hairstyle. "}],
["f21", "DashedAcceptabilityJudgment", {s: "We often photographed his partner at the scene of the crime."}],
["f22", "DashedAcceptabilityJudgment", {s: "We secretly recorded her friends at the park."}],
["f23", "DashedAcceptabilityJudgment", {s: "We quietly distracted her sisters from the boy in the room."}],
["f24", "DashedAcceptabilityJudgment", {s: "We forcefully restrained his father from punching the thief"}],
["f25", "DashedAcceptabilityJudgment", {s: "We accidently endangered his team in the barren desert."}],
["f26", "DashedAcceptabilityJudgment", {s: "We really inspired his team before their big win."}],
["f27", "DashedAcceptabilityJudgment", {s: "We often reminder her friends about the new books."}],
["f28", "DashedAcceptabilityJudgment", {s: "We openly forgave her friend for her sins."}],
["f29", "DashedAcceptabilityJudgment", {s: "We frequently recorded his boss on the set."}],
["f30", "DashedAcceptabilityJudgment", {s: "The soothing tea that the nervous student drank was imported from India."}],
["f31", "DashedAcceptabilityJudgment", {s: "The annual report that the businessman read was emailed to the manager."}],
["f32", "DashedAcceptabilityJudgment", {s: "The harsh report that the wealthy banker read was discussed in all of the newspapers."}],
["f33", "DashedAcceptabilityJudgment", {s: "The safety net that the brave policeman used was made of synthetic material."}],
["f34", "DashedAcceptabilityJudgment", {s: "The music video that the hip rapper made was shown on national television."}],
["f35", "DashedAcceptabilityJudgment", {s: "The self-portrait that the famous artist painted was sold at a very high price"}],
["f36", "DashedAcceptabilityJudgment", {s: "The TV commercial that the brave soldier appeared in was broadcast on national television."}],
["f37", "DashedAcceptabilityJudgment", {s: "The broken zipper that the skilled tailor tried to fix was replaced with a new one."}],
["f38", "DashedAcceptabilityJudgment", {s: "The security system that the police officer used was recently installed in the airport."}],
["f39", "DashedAcceptabilityJudgment", {s: "The slanderous accusation that the wealthy executive disregarded was full of inaccurate information."}],
["f40", "DashedAcceptabilityJudgment", {s: "The brief memo that the studious schoolgirl noticed was posted the notice board."}],
["f41", "DashedAcceptabilityJudgment", {s: "The thank you letter that the helpful secretary received was sent from a very important client."}],
["f42", "DashedAcceptabilityJudgment", {s: "The sharp needle that the flustered nurse used was contaminated with several strands of bacteria."}],
["f43", "DashedAcceptabilityJudgment", {s: "The documentary film that the famous actor starred in was shown in all of the major theaters."}],
["f44", "DashedAcceptabilityJudgment", {s: "The new medication that the sick patient took was very expensive for the insurance companies."}],
["f45", "DashedAcceptabilityJudgment", {s: "The newspaper article that the rich executive read was quite misleading about the facts."}],
["f46", "DashedAcceptabilityJudgment", {s: "The written testimony that the eye-witness read was reviewed by the lawyers."}],
["f47", "DashedAcceptabilityJudgment", {s: "The reference letter that the job applicant submitted was written by a recent employer."}],
["f48", "DashedAcceptabilityJudgment", {s: "The hilarious movie that the aspiring actor appeared in was a major hit in the theaters"}],


];
